# Generated by Django 4.1.7 on 2023-03-12 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, default=44600, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('property_face', models.CharField(choices=[('0', 'N/A'), ('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('NE', 'North-East'), ('NW', 'North-West'), ('SE', 'South-East'), ('SW', 'South-West')], default='P', max_length=20)),
                ('build_year', models.DateField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, default=0)),
                ('bathroom', models.IntegerField(blank=True, default=0)),
                ('garage', models.IntegerField(blank=True, default=0)),
                ('floors', models.IntegerField(blank=True, default=0)),
                ('area', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('list_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACTIVE'), ('S', 'SOLD')], default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('order', models.PositiveIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='listings.listing')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.ForeignKey(default='Any', on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_type', to='listings.propertytype', to_field='name'),
        ),
    ]
