# Generated by Django 4.1.7 on 2023-03-10 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, default=44600, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('property_face', models.CharField(choices=[('1', 'N/A'), ('2', 'North'), ('3', 'East'), ('4', 'West'), ('5', 'South'), ('6', 'North-East'), ('7', 'North-West'), ('8', 'South-East'), ('9', 'South-West')], default='1', max_length=20)),
                ('build_year', models.DateField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, default=0)),
                ('bathroom', models.IntegerField(blank=True, default=0)),
                ('garage', models.IntegerField(blank=True, default=0)),
                ('floors', models.IntegerField(blank=True, default=0)),
                ('area', models.CharField(max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, default='default_house.jpg', upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, default='default_house.jpg', upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, default='default_house.jpg', upload_to='photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, default='default_house.jpg', upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city', models.ForeignKey(default='Any', on_delete=django.db.models.deletion.DO_NOTHING, to='listings.city', to_field='name')),
                ('property_type', models.ForeignKey(default='Any', on_delete=django.db.models.deletion.DO_NOTHING, to='listings.propertytype', to_field='name')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
