# Generated by Django 4.1.7 on 2023-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='build_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
