# Generated by Django 4.1.7 on 2023-03-10 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.AddField(
            model_name='listing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.ForeignKey(default='Any', on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_type', to='listings.propertytype', to_field='name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realtors', to='realtors.realtor'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
