# Generated by Django 4.1.7 on 2023-03-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_city_listing_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
    ]
